
title: "Threat Actor Info"
description: "A comprehensive wiki on threat actors"
baseurl: ""
url: "https://WellKnitTech.github.io"
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

